MycroftAI/lingua-franca

lingua_franca/lang/parse_en.py, test/test_parse.py
same as https://github.com/MycroftAI/mycroft-core/pull/2300
fixes #21
=> bugfix(datetime_None

lingua_franca/lang/common_data_pt.py, lingua_franca/lang/parse_pt.py, test/test_parse_pt.py
splitting #17 in smaller PRs
improves logic for get_gender_pt, logic expanded to handle all cases
implemented in a way easy for re use across languages that share the same basic rules
=> improve get_gender PT

lingua_franca/lang/parse_en.py, test/test_parse.py
partially fixes #7 
this PR makes the extracted date correct and sets it to 22 pm, but the remainder is imperfect
some later code seems to depend on "tonight" being present in the remainder, some code refactor is in order, documented in unittests
=> handle extracting "tonight"/"at night"

.travis.yml
This removes the old python 3.4 version from the test suite and adds python 3.8. It also updates the pytest command to only scan the test folder for tests.
=> Remove Python 3.4 from autotest and add Python 3.8

lingua_franca/lang/parse_da.py, lingua_franca/lang/parse_de.py, lingua_franca/lang/parse_fr.py, lingua_franca/lang/parse_pt.py, lingua_franca/lang/parse_sv.py, test/test_parse_fr.py
For some languages, the definition of `extractnumber_xx` was incompatible with the use of `extract_numbers_generic` since it lacks `short_scale` and `ordinals` keyword args.
This PR fix this.
It also updates the `extractnumber_fr` when no number has been found on the given text by returning `False` instead of a normalized string to make it in sync with all other `extractnumber_xx` methods in other languages which return a number or False if no number has been parsed. Doing so handle cases such as `extractnumbers('2 heures')` which failed otherwise.
=> fix: extractnumber_xx API incompatibility

lingua_franca/lang/format_en.py, lingua_franca/lang/format_es.py, lingua_franca/lang/format_fr.py, lingua_franca/lang/format_it.py, lingua_franca/lang/format_pt.py, test/test_format.py, test/test_format_es.py, test/test_format_fr.py, test/test_format_it.py, test/test_format_pt.py
Alter format.pronounce_number_en() to parse the decimal part using strings and characters rather than math.
Bug was due to int comparisons clobbering small numbers.
Closes #75
=> fix #75 pronounce_number fails on num < 1.0

lingua_franca/lang/parse_da.py, lingua_franca/lang/parse_de.py, lingua_franca/lang/parse_en.py, lingua_franca/lang/parse_es.py, lingua_franca/lang/parse_it.py, lingua_franca/lang/parse_nl.py, lingua_franca/lang/parse_pt.py, lingua_franca/lang/parse_sv.py, test/test_parse.py, test/test_parse_da.py, test/test_parse_de.py, test/test_parse_es.py, test/test_parse_it.py, test/test_parse_nl.py, test/test_parse_pt.py, test/test_parse_sv.py
`extract_number()` helpers (`extractnumber_en()` and so forth):
- convert input string to lowercase before parsing
- bug not present in `extractnumber_fr()`
-----
Same/similar change to all but one parser. This could be handled as a
one-liner in the top-level functions, but somebody might import the
lang-specific helpers someday, and this bug would be a nasty surprise.
closes #80
=> fix #80 - capital letters break extract_number

readme.md
Address #101 by adding a step-by-step contributor guide from signing the CLA through to submitting a PR (and helping review others :smile:).
Reviews, edits and additions warmly welcomed!
Is the main README the right place for this or should we split it out into a `CONTRIBUTING.md`?
=> Issues-101 - Add step-by-step contributing guide

lingua_franca/lang/parse_da.py, lingua_franca/lang/parse_de.py, lingua_franca/lang/parse_es.py, lingua_franca/lang/parse_nl.py, lingua_franca/lang/parse_sv.py, test/test_parse_da.py, test/test_parse_de.py, test/test_parse_es.py, test/test_parse_nl.py, test/test_parse_sv.py
The use of `date_found()` was corrected in some languages. This adds the `()` in a bunch of places and adds basic unittests for the return of `None`.
Should resolve #117
=> Make sure extract_datetime() returns None for all languages

lingua_franca/lang/format_en.py, lingua_franca/lang/format_es.py, lingua_franca/lang/format_fr.py, lingua_franca/lang/format_it.py, lingua_franca/lang/format_pt.py, lingua_franca/lang/parse_en.py
Without this MR at least Python 3.8 will complain:
```
/usr/lib/python3.8/site-packages/lingua_franca/lang/format_en.py:293: SyntaxWarning: "is" with a literal. Did you mean "=="?
if abs(num) < 1.0 and (result is "minus " or not result):
/usr/lib/python3.8/site-packages/lingua_franca/lang/format_pt.py:108: SyntaxWarning: "is" with a literal. Did you mean "=="?
if abs(num) < 1.0 and (result is "menos " or not result):
/usr/lib/python3.8/site-packages/lingua_franca/lang/format_it.py:387: SyntaxWarning: "is" with a literal. Did you mean "=="?
if abs(num) < 1.0 and (result is "meno " or not result):
/usr/lib/python3.8/site-packages/lingua_franca/lang/format_es.py:197: SyntaxWarning: "is" with a literal. Did you mean "=="?
if abs(num) < 1.0 and (result is "menos " or not result): …
```
=> Fix SyntaxWarning where 'is' is used rather than '=='

lingua_franca/lang/parse_de.py, lingua_franca/parse.py, test/test_parse_de.py
In the current implementation it is not possible (for german clients) to parse german duration phrases without running into exceptions like gras64 described [here](https://github.com/MycroftAI/mycroft-timer/issues/70)
I added the specific lines to parse_de.py and rewrote the regex pattern and the time_units / {unit} handling, which could be adopted across the language spectrum.
In order to take affect **additional edits** in [mycroft-core/mycroft/util/parse.py](https://github.com/MycroftAI/mycroft-core/blob/d6cbccc0cbfbf6b540830aab4c15a32adf67b9bf/mycroft/util/parse.py#L222) have to be made, like 
```
if lang_code == "de":
return extract_duration_de(text)
_log_unsupported_language(lang_code, ['en, de'])
```
With the [PR on skill-timer](https://github.com/MycroftAI/mycroft-timer/pull/77) …
=> Small fix to enable german duration parsing

lingua_franca/lang/parse_cs.py, lingua_franca/lang/parse_de.py, lingua_franca/lang/parse_en.py
This PR reduces the runtime of `extract_duration` by combining the two regex calls.
=> reduce runtime for duration parsing

setup.py
Bump Lingua Franca version number and supported Python versions.
This will be the final v0.2.* release before the major refactor is merged for v0.3.0
=> bump to v0.2.3

test/test_format_cs.py
Address issue #139
Removed for lops
Run tests only for "cs-cz"
All test passed
=> test_format_cs: remove testing for other languages

MANIFEST.in, setup.py
Key files are not being included in the source distribution. This adds a `MANIFEST.in` to explicitly include them.
We hit the same issue with the Messagebus Client recently and installations will fail without them present.
=> explicitly add files to source dist package

lingua_franca/lang/parse_nl.py, test/test_parse_nl.py
Adds extract_duration support for dutch  (nl-nl)
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
Added some test for extract_duration in dutch (nl-nl)
=> Added extract_duration support for dutch

lingua_franca/__init__.py, lingua_franca/config.py, lingua_franca/internal.py, test/test_localizer.py
This branch (squash pls) adds `config.py` (eventually #128) with one variable: `load_langs_on_demand`.
When this variable is `True`, the localized function caller will - if and *only* if a language is passed which is not loaded - load the language, call the function, and unload the language.
At the moment, this is pretty fast, though it might need to be revisited if some languages become truly bloated with resource files.
This is only desirable in certain use cases, but, for instance, the absence of this flag was an obstacle for @JarbasAl's modular `text2speech` package, which doesn't always know the language it wants ahead of time.
I've tested this PR against that module, and it solves the problem. I want to stress that use cases like Mycroft, which prefer to utilize at most one engine …
=> config.load_langs_on_demand: permits on-the-fly loading/unloading, to facilitate proc-gen use cases

.github/workflows/pytest.yml, lingua_franca/internal.py, setup.py, test/test_localizer.py
We held out almost two whole months! 3.5 is donezo, though, and the supported versions contain some delicious syntactic sugar. To aid with the Catalan localization, a new wrapper has been introduced which takes advantage of that sugar. Furthermore, the 0.3 rebase *attempted* to utilize the newer `ModuleNotFoundError`, but 3.5 didn't have it.
Goodbye, 3.5!
=> drop support for python 3.5 (EOL)

lingua_franca/lang/parse_fr.py, test/test_parse_fr.py
Add extract_duration support for french language (inspired from what was done for german).
Unit tests added under ` test/test_parse_fr.py`
=> Add extract_duration for french

lingua_franca/lang/common_data_en.py, lingua_franca/lang/parse_en.py, test/test_parse.py
- case preservation in extract_duration
- extract_datetime number words support
- number replacement in normalize
- adds better support for ordinals
fixes #145
fixes #143 
fixes #135
fixed #153
=> bug fix #145 #143 #135 #153

pre-spinoff-credits.md, readme.md
Anybody who contributed to this codebase before it was spun off from Mycroft-core is (obviously) missing from `git log`.
I've attempted to list them.
=> add file to credit "pre-spinoff" contributors

MANIFEST.in, setup.py
I've removed the `tests` directory from `setup.py`, and included `test/ *.py` via `MANIFEST.in`, which is intended to ensure that tests are included with source distributions, but are not installed to the user's system.
I'm not 100% sure I've done this right, but when I make the sdist and unpack it, both `setup.py test` and `pytest test/` succeed as expected.
(see #178)
=> fix #178: don't install tests, just include

lingua_franca/internal.py
The function localizer (`@localized_function`) accepts a parameter, `run_own_code_on`, which can be an error or a list of errors. There is a sanity check at the top of the function, before the wrapper begins.
This parameter is almost always left empty. Its default was already `[None]`, to avoid unnecessary casts to list, so we can skip the whole sanity check and save a bunch of ops.
=> localized_function(): don't validate absent param

setup.py
The LF version in `setup.py` was still listed as a release candidate when the `release/v0.4.0 tag` was made. Unfortunately this means that PyPI would consider it v0.4.0rc1 rather than the full 0.4.0. 
This PR bumps the version up a patch number so we can re-tag and have matching versions for PyPI.
=> Bump version to v0.4.1

lingua_franca/format.py, lingua_franca/parse.py
This is a quick clean up of public docstrings in the primary parse.py and format.py files.
- uses a consistent description for the `lang` parameter
- adds some missing arguments
- add type hints for `fuzzy_match` where the input args are self-explanatory
- autopep8 formatting
Easiest is eyeballs here I think.
=> Clean up of public docstrings

lingua_franca/parse.py
Small clarification - returned data will be in the "local timezone" which will be either the timezone of the datetime object passed into the method OR the configured default timezone. With the word "user" included it sounded like the return value would always be in the user's configured default timezone.
=> Clarify docstring that valid tz won't be mutated

lingua_franca/res/text/it-it/date_time.json, lingua_franca/res/text/it-it/date_time_test.json
d.c. is the opposite
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
=> In italian b.c. translates in a.C.

lingua_franca/lang/parse_sv.py, test/test_parse_sv.py
This adds an initial version of `extract_duration_sv`. The parser is quite simple and will likely need to be extended to handle more complex cases. But this works for many normal sentences.
Ensure unittests work
=> Add extract_duration for Swedish

requirements.txt
Allow for system to use newer versions of `python-dateutil` 
Fix #227 
Automated testing should pass
=> Soften version requirement for python-dateutil

lingua_franca/lang/parse_en.py, test/test_parse.py
Fixes #224 - extract_datetime parsing of phrases like "in 2007"
Whilst this isn't ideal behaviour, it is better than returning a time.
This is a port of https://github.com/OpenVoiceOS/ovos-lingua-franca/pull/9
Test added
=> Fix #224 - parsing 'in 2007'

lingua_franca/lang/parse_cs.py, lingua_franca/lang/parse_de.py, lingua_franca/lang/parse_fa.py, lingua_franca/lang/parse_fr.py, lingua_franca/lang/parse_nl.py, lingua_franca/lang/parse_pl.py, lingua_franca/parse.py
Adopting an addition from #202 across all languages with a localized `extract_duration` method. This adds detail on the length of durations supported.
Also some other minor docstring cleanup but not a comprehensive fix of all docstrings.
No code changes.
=> Add detail on supported durations to extract_duration

test/test_format.py, test/test_format_cs.py, test/test_format_da.py, test/test_format_de.py, test/test_format_fa.py, test/test_format_fr.py, test/test_format_hu.py, test/test_format_nl.py, test/test_format_sl.py, test/test_format_sv.py
Minor cleanup - for some reason a nice_time function signature was left in as a comment this has been copied across to multiple languages.
Noticed when reviewing #212
No functional changes - tests should pass.
=> Remove random commented out code

lingua_franca/lang/parse_en.py, test/test_parse.py
Default_time argument sometimes was ignored, and sometimes was wrongly used
Backport of https://github.com/OpenVoiceOS/ovos-lingua-franca/pull/21
Fixes #229
Unit tests included
=> Fix default_time argument on extract_datetime

.github/workflows/push.yml
This makes sure the update isn't run unless the publishing step was
performed. Currently the Master branch will report CICD failure if no new
version was published, this is now prevented by checking if a version has
been set.
- [ x ] Bugfix
=> Fix CICD job on master: Only update mycroft-core after tag and release

requirements.txt
Just bumps the python-dateutil version to latest v2.8.2
Fixes #234 
Unit tests should continue to pass.
=> Bump python-dateutil to latest v2.8.2
